% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Analiza uspjeha učenika},
  pdfauthor={`Drim Tim' - Danijel Kovačević, Luka Panđa, Martin Ante Rogošić, Marko Sršić},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Analiza uspjeha učenika}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{SAP - projekt}
\author{`Drim Tim' - Danijel Kovačević, Luka Panđa, Martin Ante Rogošić,
Marko Sršić}
\date{1.1.2025.}

\begin{document}
\maketitle

\hypertarget{uvod}{%
\section{1. Uvod}\label{uvod}}

Utjecaj različitih čimbenika na školski uspjeh učenika je oduvijek bila
jedna od najzanimljivijih tema za istraživače iz raznih područja; kako
je pohađanje škole i polaganje ispita sastavni dio života većine ljudi u
današnjem modernom dobu, interes za dublje razumijevanje individualnih,
sociodemografskih i društvenih karakteristika koje oblikuju akademska
postignuća učenika/studenata neprestano raste. Takva istraživanja mogu
pridonijeti stvaranju pravednijeg i učinkovitijeg obrazovnog sustava
koji može bolje odgovoriti na potrebe različitih skupina učenika.

U sklopu projekta na kolegiju ``Statistička analiza podataka'', grupa
``Drim Tim'' pokušat će na temelju podataka o različitim značajkama za
više od 350 učenika iz dviju portugalskih srednjih škola odgovoriti na
neka zanimljiva istraživačka pitanja koja će čitatelju približiti odnos
i utjecaj tih značajki na ispitni uspjeh iz matematike i portugalskog
jezika.

Analiza obuhvaća korištenje različitih statističkih metoda i tehnika te
je zbog toga podijeljena u dva poglavlja. U 2. poglavlju se postupcima
deskriptivne statistike nastoji dobiti bolji uvid u korišteni podatkovni
skup i otkriti eventualne nedostajuće ili stršeće podatke. U tu svrhu će
se provjeriti priroda značajki (jesu li kategorijske ili numeričke),
izračunati mjere centralne tendencije i mjere rasipanja te napraviti
vizualizacija za neke ključne varijable. U 3. poglavlju su postavljena
određena istraživačka pitanja od interesa, poput ``razlika u ocjeni iz
matematike s obzirom na mjesto stanovanja'' ili ``predviđanje uspjeha na
završnom ispitu iz jezika na temelju sociodemografskih varijabli''.
Korištenjem deskriptora poput srednje vrijednosti ili varijance i
vizualizacijom postavlja se početna hipoteza čija se ispravnost
provjerava provedbom odgovarajućeg statističkog testa. Na temelju
rezultata tog statističkog testa možemo (ili ne možemo) donijeti
zaključak o hipotezi koju smo postavili.\\
Posljednje, 4. poglavlje donosi sažetak analize i
najvažnije/najzanimljivije zaključke.

\hypertarget{deskriptivna-analiza-ulaznog-skupa-podataka}{%
\section{2. Deskriptivna analiza ulaznog skupa
podataka}\label{deskriptivna-analiza-ulaznog-skupa-podataka}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# učitavanje paketa}
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

Podaci koji će nam poslužiti za statističku analizu uspjeha učenika
prikupljeni su školske godine 2005/2006. u dvije portugalske srednje
škole - ``Gabriel Pereira'' (GP) i ``Mousinho da Silveira'' (MS).
Upoznajmo se sa značajkama podatkovnog skupa.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"student\_data.csv"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   school sex age address famsize Pstatus Medu Fedu     Mjob     Fjob     reason
## 1     GP   F  18       U     GT3       A    4    4  at_home  teacher     course
## 2     GP   F  17       U     GT3       T    1    1  at_home    other     course
## 3     GP   F  15       U     LE3       T    1    1  at_home    other      other
## 4     GP   F  15       U     GT3       T    4    2   health services       home
## 5     GP   F  16       U     GT3       T    3    3    other    other       home
## 6     GP   M  16       U     LE3       T    4    3 services    other reputation
##   guardian traveltime studytime failures_mat failures_por schoolsup famsup
## 1   mother          2         2            0            0       yes     no
## 2   father          1         2            0            0        no    yes
## 3   mother          1         2            3            0       yes     no
## 4   mother          1         3            0            0        no    yes
## 5   father          1         2            0            0        no    yes
## 6   mother          1         2            0            0        no    yes
##   paid_mat paid_por activities nursery higher internet romantic famrel freetime
## 1       no       no         no     yes    yes       no       no      4        3
## 2       no       no         no      no    yes      yes       no      5        3
## 3      yes       no         no     yes    yes      yes       no      4        3
## 4      yes       no        yes     yes    yes      yes      yes      3        2
## 5      yes       no         no     yes    yes       no       no      4        3
## 6      yes       no        yes     yes    yes      yes       no      5        4
##   goout Dalc Walc health absences_mat absences_por G1_mat G2_mat G3_mat G1_por
## 1     4    1    1      3            6            4      5      6      6      0
## 2     3    1    1      3            4            2      5      5      6      9
## 3     2    2    3      3           10            6      7      8     10     12
## 4     2    1    1      5            2            0     15     14     15     14
## 5     2    1    2      5            4            0      6     10     10     11
## 6     2    1    2      5           10            6     15     15     15     12
##   G2_por G3_por
## 1     11     11
## 2     11     11
## 3     13     12
## 4     14     14
## 5     13     13
## 6     12     13
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 370  39
\end{verbatim}

Imamo podatke o 370 učenika i 39 značajki koje ih opisuju. Te značajke
su:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "school"       "sex"          "age"          "address"      "famsize"     
##  [6] "Pstatus"      "Medu"         "Fedu"         "Mjob"         "Fjob"        
## [11] "reason"       "guardian"     "traveltime"   "studytime"    "failures_mat"
## [16] "failures_por" "schoolsup"    "famsup"       "paid_mat"     "paid_por"    
## [21] "activities"   "nursery"      "higher"       "internet"     "romantic"    
## [26] "famrel"       "freetime"     "goout"        "Dalc"         "Walc"        
## [31] "health"       "absences_mat" "absences_por" "G1_mat"       "G2_mat"      
## [36] "G3_mat"       "G1_por"       "G2_por"       "G3_por"
\end{verbatim}

Vidimo da uz osnovne značajke poput škole, spola i godina imamo niz
sociodemografskih značajki (veličina obitelji, obrazovanje roditelja,
zanimanje roditelja, adresa\ldots), obrazovnih značajki (tjedno vrijeme
učenja, dodatne plaćene instrukcije\ldots), društvenih značajki
(izlasci, konzumacija alkohola\ldots) te značajke koje opisuju uspjeh
učenika na ispitima iz matematike i jezika.

(Varijable i njihovo značenje -\textgreater{} navesti sve posebno i
odrediti tip?)

\begin{itemize}
\tightlist
\item
  \emph{school} - (B) učenikova škola (`GP' ili `MS')
\item
  \emph{sex} - (B) spol (`M' - muški, `F' - ženski) \ldots.(?)
\end{itemize}

Funkcijom \emph{summary} za numeričke podatke možemo dobiti sažetak 5
brojeva (min, max, Q1, medijan, Q3) i srednju vrijednost:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(df[}\FunctionTok{sapply}\NormalTok{(df, is.numeric)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age             Medu          Fedu         traveltime      studytime    
##  Min.   :15.00   Min.   :0.0   Min.   :0.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:16.00   1st Qu.:2.0   1st Qu.:2.000   1st Qu.:1.000   1st Qu.:1.000  
##  Median :17.00   Median :3.0   Median :3.000   Median :1.000   Median :2.000  
##  Mean   :16.58   Mean   :2.8   Mean   :2.557   Mean   :1.446   Mean   :2.043  
##  3rd Qu.:17.00   3rd Qu.:4.0   3rd Qu.:3.750   3rd Qu.:2.000   3rd Qu.:2.000  
##  Max.   :22.00   Max.   :4.0   Max.   :4.000   Max.   :4.000   Max.   :4.000  
##   failures_mat     failures_por        famrel         freetime    
##  Min.   :0.0000   Min.   :0.0000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:4.000   1st Qu.:3.000  
##  Median :0.0000   Median :0.0000   Median :4.000   Median :3.000  
##  Mean   :0.2784   Mean   :0.1324   Mean   :3.935   Mean   :3.224  
##  3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:5.000   3rd Qu.:4.000  
##  Max.   :3.0000   Max.   :3.0000   Max.   :5.000   Max.   :5.000  
##      goout            Dalc            Walc           health     
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:2.000   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:3.000  
##  Median :3.000   Median :1.000   Median :2.000   Median :4.000  
##  Mean   :3.116   Mean   :1.484   Mean   :2.295   Mean   :3.562  
##  3rd Qu.:4.000   3rd Qu.:2.000   3rd Qu.:3.000   3rd Qu.:5.000  
##  Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000  
##   absences_mat     absences_por        G1_mat          G2_mat     
##  Min.   : 0.000   Min.   : 0.000   Min.   : 3.00   Min.   : 0.00  
##  1st Qu.: 0.000   1st Qu.: 0.000   1st Qu.: 8.00   1st Qu.: 9.00  
##  Median : 4.000   Median : 2.000   Median :11.00   Median :11.00  
##  Mean   : 5.381   Mean   : 3.632   Mean   :10.89   Mean   :10.75  
##  3rd Qu.: 8.000   3rd Qu.: 6.000   3rd Qu.:13.00   3rd Qu.:13.00  
##  Max.   :75.000   Max.   :32.000   Max.   :19.00   Max.   :19.00  
##      G3_mat          G1_por          G2_por          G3_por     
##  Min.   : 0.00   Min.   : 0.00   Min.   : 5.00   Min.   : 0.00  
##  1st Qu.: 8.00   1st Qu.:10.00   1st Qu.:11.00   1st Qu.:11.00  
##  Median :11.00   Median :12.00   Median :12.00   Median :13.00  
##  Mean   :10.46   Mean   :12.14   Mean   :12.27   Mean   :12.55  
##  3rd Qu.:14.00   3rd Qu.:14.00   3rd Qu.:14.00   3rd Qu.:14.00  
##  Max.   :20.00   Max.   :19.00   Max.   :19.00   Max.   :19.00
\end{verbatim}

Ovo je korisno za značajke poput \emph{age}, \emph{absences} i
\emph{G1}-\emph{G3}; primjerice za značajku \emph{age} vidimo da je
raspon godina učenika {[}15, 22{]}, medijan 17 godina i srednja
vrijednost 16.58 godina. Ipak, ovo nije previše korisno za značajke koje
su po strukturi numeričke (jer su njihove vrijednosti reprezentirane
brojevima), ali su po prirodi kategorijske (npr. \emph{Medu} poprima
vrijednosti od 0 do 4 koje reprezentiraju ordinalnu skalu različitih
razina obrazovanja). Podaci su ovako enkodirani kako bi se olakšalo
njihovo korištenje s algoritmima strojnog učenja.

Zato ćemo za te numeričke značajke pogledati zastupljenost pojedinih
kategorija, zajedno uz kategorijske značajke (za koje nismo mogli dobiti
gornji sažetak):

\hypertarget{to-do}{%
\section{TO-DO}\label{to-do}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# prije provjere zastupljenosti potrebno je faktorizirati kategorijske značajke}

\CommentTok{\#df\_factor \textless{}{-} lapply(df, function(x) \{}
\CommentTok{\#  if (is.character(x) || is.factor(x)) \{}
\CommentTok{\#    as.factor(x)}
\CommentTok{\#  \} else \{}
\CommentTok{\#    x}
\CommentTok{\#  \}}
\CommentTok{\#\})}

\CommentTok{\#table(df\_factor)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#help(table)}
\end{Highlighting}
\end{Shaded}

\hypertarget{istraux17eivaux10dka-pitanja}{%
\section{3. Istraživačka pitanja}\label{istraux17eivaux10dka-pitanja}}

\hypertarget{jesu-li-prosjeux10dne-ocjene-iz-matematike-razliux10dite-izmeux111u-spolova}{%
\subsubsection{3.1. Jesu li prosječne ocjene iz matematike različite
između
spolova?}\label{jesu-li-prosjeux10dne-ocjene-iz-matematike-razliux10dite-izmeux111u-spolova}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_frame }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"student\_data.csv"}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{male\_data }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data\_frame, sex }\SpecialCharTok{==} \StringTok{"M"}\NormalTok{)}

\NormalTok{male\_data }\OtherTok{\textless{}{-}}\NormalTok{ male\_data}\SpecialCharTok{$}\NormalTok{G3\_mat}
  
  
\NormalTok{female\_data }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data\_frame, sex }\SpecialCharTok{==} \StringTok{"F"}\NormalTok{)}
\NormalTok{female\_data }\OtherTok{\textless{}{-}}\NormalTok{ female\_data}\SpecialCharTok{$}\NormalTok{G3\_mat}
\end{Highlighting}
\end{Shaded}

Kako bismo odgovorili na pitaje postoji li razlika u konačnim ocjenama
među spolovima prvo moramo odraditi deskriptivnu statistiku.

Za početak napravimo box plotove za ocjene ovih dvaju populacija.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(male\_data, female\_data, }\AttributeTok{main=}\StringTok{"Box plot"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_dokument_files/figure-latex/unnamed-chunk-9-1.pdf}

Sa boxplota vidimo da postoji mala razlika u medianima uzoraka. Dodatno
zanimljivo je uočiti da za obje populacije boxplot je skoro jednak samo
je jedna od populacija translatirana. To nas navodi na hipotezu da su
distribucije ovih populacija iste smo ne poravnate.

Pogledajmo jesu li podatci normalni. Za početak pogledajmo histograme.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}

\FunctionTok{hist}\NormalTok{(male\_data)}

\FunctionTok{hist}\NormalTok{(female\_data)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_dokument_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

S histograma je jasno da podatci nisu normalni stoga na njih u ovakvom
obliku nećemo moći primjeniti parametarske testove koji pretpostavljaju
normalnost populacije.

To potvrđuju i Q-Q plotovi ovih uzoraka.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}

\FunctionTok{qqplot}\NormalTok{(male\_data,}\FunctionTok{rnorm}\NormalTok{(male\_data), }\AttributeTok{main=}\StringTok{"Q{-}Q plot podataka za mušku populaciju"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(}\FunctionTok{rnorm}\NormalTok{(male\_data), }\AttributeTok{col=}\StringTok{"red"}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}

\FunctionTok{qqplot}\NormalTok{(female\_data,}\FunctionTok{rnorm}\NormalTok{(female\_data), }\AttributeTok{main=}\StringTok{"Q{-}Q plot podataka za žensku populaciju"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(}\FunctionTok{rnorm}\NormalTok{(female\_data), }\AttributeTok{col=}\StringTok{"red"}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_dokument_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Q-Q plotovi definitivno potvrđuju da podatci nijednog od uzoraka nisu
normalni.

S obzirom da podatci nisu normalni, prvo ćemo se poslužiti nekim
neparametarskim postupkom. Nakon toga pokušati ćemo izmijeniti uzorke
(izbacivanjem ekstrema) i pokušati primjeniti neki parametarski
postupak. Idealno bi bilo koristiti Kolmogorov-Smirnovljev test, međutim
zbog diskretnosti podataka on nije prikladan, iako bi on izravno dao
odgovor na postavljeno pitanje. Umjesto toga upotrijebit Mann-Whitney U
test koji će nam reći postoji li statistički zančajna razlika u
medijanima dviju distribucija sličnog oblika. Budući da iz histograma
vidimo da su distribucije sličnog oblika on U test je ovdje prikladan.
Dodatno normalizacijom podataka možemo vidjeti da su histogrami sličniji
ako standardiziramo podatke, što će smanjiti vjerojatnost pogreške

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{hist}\NormalTok{(}\FunctionTok{scale}\NormalTok{(male\_data))}
\FunctionTok{hist}\NormalTok{(}\FunctionTok{scale}\NormalTok{(female\_data))}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_dokument_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Konačno provedimo test

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{wilcox.test}\NormalTok{(}\FunctionTok{scale}\NormalTok{(male\_data), }\FunctionTok{scale}\NormalTok{(female\_data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  scale(male_data) and scale(female_data)
## W = 16207, p-value = 0.4046
## alternative hypothesis: true location shift is not equal to 0
\end{verbatim}

Iz p vrijednosti 0.406 možemo zaključiti da ne postoji statistički
značajna razlika u završnim ocjenama iz matematike između splova.
Zanimljivo je međutim uočiti da U test nad ne standardiziranim podatcima
daje drugačije rezultate.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{wilcox.test}\NormalTok{(male\_data, female\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  male_data and female_data
## W = 19719, p-value = 0.009412
## alternative hypothesis: true location shift is not equal to 0
\end{verbatim}

S ovom novom p vrijednosti zaključili bismo da postoji značaja razlika u
ocjenama. No budući da je oblik distribucije sličniji za normalizirane
podatke to je rezultat kojeg odabiremo.

\hypertarget{postoji-li-razlika-u-prvoj-ocjeni-iz-matematike-s-obzirom-na-mjesto-stanovanja}{%
\subsubsection{3.2. Postoji li razlika u prvoj ocjeni iz matematike s
obzirom na mjesto
stanovanja?}\label{postoji-li-razlika-u-prvoj-ocjeni-iz-matematike-s-obzirom-na-mjesto-stanovanja}}

\hypertarget{pregled-podataka}{%
\section{Pregled podataka}\label{pregled-podataka}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{student\_data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}student\_data.csv\textquotesingle{}}\NormalTok{)}
\FunctionTok{head}\NormalTok{(student\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   school sex age address famsize Pstatus Medu Fedu     Mjob     Fjob     reason
## 1     GP   F  18       U     GT3       A    4    4  at_home  teacher     course
## 2     GP   F  17       U     GT3       T    1    1  at_home    other     course
## 3     GP   F  15       U     LE3       T    1    1  at_home    other      other
## 4     GP   F  15       U     GT3       T    4    2   health services       home
## 5     GP   F  16       U     GT3       T    3    3    other    other       home
## 6     GP   M  16       U     LE3       T    4    3 services    other reputation
##   guardian traveltime studytime failures_mat failures_por schoolsup famsup
## 1   mother          2         2            0            0       yes     no
## 2   father          1         2            0            0        no    yes
## 3   mother          1         2            3            0       yes     no
## 4   mother          1         3            0            0        no    yes
## 5   father          1         2            0            0        no    yes
## 6   mother          1         2            0            0        no    yes
##   paid_mat paid_por activities nursery higher internet romantic famrel freetime
## 1       no       no         no     yes    yes       no       no      4        3
## 2       no       no         no      no    yes      yes       no      5        3
## 3      yes       no         no     yes    yes      yes       no      4        3
## 4      yes       no        yes     yes    yes      yes      yes      3        2
## 5      yes       no         no     yes    yes       no       no      4        3
## 6      yes       no        yes     yes    yes      yes       no      5        4
##   goout Dalc Walc health absences_mat absences_por G1_mat G2_mat G3_mat G1_por
## 1     4    1    1      3            6            4      5      6      6      0
## 2     3    1    1      3            4            2      5      5      6      9
## 3     2    2    3      3           10            6      7      8     10     12
## 4     2    1    1      5            2            0     15     14     15     14
## 5     2    1    2      5            4            0      6     10     10     11
## 6     2    1    2      5           10            6     15     15     15     12
##   G2_por G3_por
## 1     11     11
## 2     11     11
## 3     13     12
## 4     14     14
## 5     13     13
## 6     12     13
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{columns }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}G1\_mat\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}address\textquotesingle{}}\NormalTok{)}
\NormalTok{grades }\OtherTok{\textless{}{-}}\NormalTok{ student\_data[columns]}
\end{Highlighting}
\end{Shaded}

\hypertarget{vizualizacija}{%
\section{Vizualizacija}\label{vizualizacija}}

Box plot prve ocjene iz matematike s obzirom na mjesto stanovanja.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{grades}\SpecialCharTok{$}\NormalTok{address }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(grades}\SpecialCharTok{$}\NormalTok{address)}

\FunctionTok{plot}\NormalTok{(G1\_mat }\SpecialCharTok{\textasciitilde{}}\NormalTok{ address, grades)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_dokument_files/figure-latex/unnamed-chunk-17-1.pdf}

Uz pomoć našeg box plot-a možemo očekivati da neće biti razlike u prvoj
ocjeni iz matematike s obzirom na mjesto stanovanja. No kako bismo to
statistički zaključili, provodimo dva različita testa, hi-kvadrat test
nezavisnosti/homogenosti podataka, te ANOVA-u.

\hypertarget{hi-kvadrat-test-nezavisnostihomogenosti-podataka}{%
\section{hi-kvadrat test nezavisnosti/homogenosti
podataka}\label{hi-kvadrat-test-nezavisnostihomogenosti-podataka}}

Kako bismo mogli primjeniti hi-kvadrat test nezavisnosti/homogenosti
podataka, sve očekivane frekvencije moraju imati vrijednost veću ili
jednaku 5. Iz tog razloga prvo provjeravamo broj očekivanih vrijednosti
manjih od 5. Ako jedna ili više takvih vrijednosti postoji, ne možemo
primjeniti ovaj test, te moramo razmatrati alternativu.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{group }\OtherTok{\textless{}{-}}\NormalTok{ grades}\SpecialCharTok{$}\NormalTok{address}
\NormalTok{g1\_mat }\OtherTok{\textless{}{-}}\NormalTok{ grades}\SpecialCharTok{$}\NormalTok{G1\_mat}

\NormalTok{contingency\_table }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(group, g1\_mat)}

\NormalTok{N }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(group)}
\NormalTok{num }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(group)}
\NormalTok{num\_R }\OtherTok{\textless{}{-}}\NormalTok{ num[}\StringTok{\textquotesingle{}R\textquotesingle{}}\NormalTok{]}
\NormalTok{num\_U }\OtherTok{\textless{}{-}}\NormalTok{ num[}\StringTok{\textquotesingle{}U\textquotesingle{}}\NormalTok{]}

\NormalTok{counter }\OtherTok{\textless{}{-}} \DecValTok{0}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{ncol}\NormalTok{(contingency\_table)) \{}
\NormalTok{  value }\OtherTok{\textless{}{-}} \DecValTok{0}
  \ControlFlowTok{for}\NormalTok{ (j }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(contingency\_table)) \{}
\NormalTok{    value }\OtherTok{\textless{}{-}}\NormalTok{ value }\SpecialCharTok{+}\NormalTok{ contingency\_table[j, i]}
\NormalTok{  \}}
  
\NormalTok{  expected\_R }\OtherTok{\textless{}{-}}\NormalTok{ N }\SpecialCharTok{*}\NormalTok{ (value }\SpecialCharTok{/}\NormalTok{ N) }\SpecialCharTok{*}\NormalTok{ (num\_R }\SpecialCharTok{/}\NormalTok{ N)}
\NormalTok{  expected\_U }\OtherTok{\textless{}{-}}\NormalTok{ N }\SpecialCharTok{*}\NormalTok{ (value }\SpecialCharTok{/}\NormalTok{ N) }\SpecialCharTok{*}\NormalTok{ (num\_U }\SpecialCharTok{/}\NormalTok{ N)}
  
  \ControlFlowTok{if}\NormalTok{ (expected\_R }\SpecialCharTok{\textless{}} \DecValTok{5}\NormalTok{) \{}
\NormalTok{    counter }\OtherTok{\textless{}{-}}\NormalTok{ counter }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{  \}}
  
  \ControlFlowTok{if}\NormalTok{ (expected\_U }\SpecialCharTok{\textless{}} \DecValTok{5}\NormalTok{) \{}
\NormalTok{    counter }\OtherTok{\textless{}{-}}\NormalTok{ counter }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{  \}}
\NormalTok{\}}

\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Postoji "}\NormalTok{, counter, }\StringTok{" očekivanih vrijednosti s vrijednošću manjom od 5, te ne možemo provesti hi{-}kvadrat test homogenosti/nezavisnosti podataka"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Postoji  12  očekivanih vrijednosti s vrijednošću manjom od 5, te ne možemo provesti hi-kvadrat test homogenosti/nezavisnosti podataka"
\end{verbatim}

\hypertarget{anova}{%
\section{ANOVA}\label{anova}}

Prvi korak prije samog provođenja ANOVA-e je provođenje Bartlett-ovog
testa nad podacima kako bismo testirali homogenost varijanci uzoraka.

Želimo testirati:\\
H0: sve su varijance jednake\\
H1: barem dvije varijance se razlikuju\\
alpha = 0.05

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Testiranje homogenosti varijanci uzoraka}
\CommentTok{\# Bartlettov test}

\NormalTok{bartlett\_test\_result }\OtherTok{\textless{}{-}} \FunctionTok{bartlett.test}\NormalTok{(G1\_mat }\SpecialCharTok{\textasciitilde{}}\NormalTok{ address, grades)}

\FunctionTok{print}\NormalTok{(bartlett\_test\_result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Bartlett test of homogeneity of variances
## 
## data:  G1_mat by address
## Bartlett's K-squared = 0.14685, df = 1, p-value = 0.7016
\end{verbatim}

Dobivši p-vrijednost 0.7016, tj. značajno veću vrijednost od
pretpostavljenje razine značajnosti (0.05), možemo zaključiti da su
varijance jednake te da nad ovim podacima možemo provesti ANOVA-u.

Prije same ANOVA-e također promatramo koliko različitih uzoraka imamo za
svaku kategoriju (U - urban te R - rural).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(grades}\SpecialCharTok{$}\NormalTok{address, }\AttributeTok{useNA =} \StringTok{\textquotesingle{}always\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    R    U <NA> 
##   81  289    0
\end{verbatim}

Želimo testirati:\\
H0: sve su srednje vrijednosti jednake\\
H1: barem dvije srednje vrijednosti se razlikuju\\
alpha = 0.05

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{anova\_result }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(G1\_mat }\SpecialCharTok{\textasciitilde{}}\NormalTok{ address, grades)}

\FunctionTok{summary}\NormalTok{(anova\_result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df Sum Sq Mean Sq F value Pr(>F)
## address       1     20   19.63   1.758  0.186
## Residuals   368   4110   11.17
\end{verbatim}

p-vrijednost našeg ANOVA testa je zadana kao Pr(\textgreater F), te
iznosi 0.186 \textgreater{} 0.05, te iz tog razloga ne možemo odbaciti
nultu hipotezu. Koristeći ANOVA test, statistički zaključujemo da prva
ocjena iz matematike ne ovisi o mjestu stanovanja.

\hypertarget{moux17eemo-li-predvidjeti-prolaz-iz-zavrux161nog-ispita-iz-jezika-na-temelju-sociodemografskih-varijabli-poput-spola-obrazovanja-roditelja-i-veliux10dine-obitelji}{%
\subsubsection{3.3. Možemo li predvidjeti prolaz iz završnog ispita iz
jezika na temelju sociodemografskih varijabli poput spola, obrazovanja
roditelja i veličine
obitelji?}\label{moux17eemo-li-predvidjeti-prolaz-iz-zavrux161nog-ispita-iz-jezika-na-temelju-sociodemografskih-varijabli-poput-spola-obrazovanja-roditelja-i-veliux10dine-obitelji}}

\hypertarget{postoji-li-razlika-u-broju-izostanaka-iz-matematike-izmeux111u-uux10denika-koji-dolaze-iz-manjih-i-veux107ih-obitelji}{%
\subsubsection{3.4. Postoji li razlika u broju izostanaka iz matematike
između učenika koji dolaze iz manjih i većih
obitelji?}\label{postoji-li-razlika-u-broju-izostanaka-iz-matematike-izmeux111u-uux10denika-koji-dolaze-iz-manjih-i-veux107ih-obitelji}}

\hypertarget{postoji-li-razlika-u-____-iz-____-s-obzirom-na-problematiux10dne-varijable-izostanci-alkohol-izlasci-romantic-partner}{%
\subsubsection{3.5. Postoji li razlika u \_\_\_\_ iz \_\_\_\_ s obzirom
na ``problematične'' varijable (izostanci, alkohol, izlasci, romantic
partner)}\label{postoji-li-razlika-u-____-iz-____-s-obzirom-na-problematiux10dne-varijable-izostanci-alkohol-izlasci-romantic-partner}}

\hypertarget{moux17ee-li-se-ambicijom-i-novcem-do-boljih-rezultata-dodatne-plaux107ene-instrukcije-ux17eeli-dodatno-viux161e-obrazovanje-schoolfamily-support}{%
\subsubsection{3.6. Može li se ambicijom i novcem do boljih rezultata
(dodatne plaćene instrukcije, želi dodatno više obrazovanje,
school/family support
\ldots)}\label{moux17ee-li-se-ambicijom-i-novcem-do-boljih-rezultata-dodatne-plaux107ene-instrukcije-ux17eeli-dodatno-viux161e-obrazovanje-schoolfamily-support}}

\hypertarget{upareni-test}{%
\subsubsection{Upareni test?}\label{upareni-test}}

\hypertarget{predviux111anje}{%
\subsubsection{Predviđanje?}\label{predviux111anje}}

\hypertarget{zakljuux10dak}{%
\section{4. Zaključak}\label{zakljuux10dak}}

\end{document}
